title: JJ BLOG
description: Ruby on Rails로 웹개발을 하고있는 웹개발자입니다.
author: JJ
github: https://github.com/jongjineee
about: Ruby on Rails로 웹개발을 하고있는 웹개발자입니다.
disqus_shortname: stackproblems
google_analytics: 
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/jongjin.lee.14"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/%EC%A2%85%EC%A7%84-%EC%9D%B4-38a15517b/"
    - icon: fa-github
      link: "https://github.com/jonjineee"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://jongjineee.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
